var moment = require('moment');

function ActiveTripsTracker() {
  this.activeTripsById = {};
  this.tripRemovalSpan = moment.duration(5, 'minutes');
  this.dashboardTripsById = {};
  this.maxDashboardTrips = 150;
  this.bookingWebsiteTripTag = 'web'; // Used to identify trips generated by demo website to ensure they show up on dashboard
}

ActiveTripsTracker.prototype.addTrip = function(trip) {
  if(this.activeTripsById.hasOwnProperty(trip.id)) {
    throw new Error('Trip ' + trip.id + ' already exists');
  }
  this.activeTripsById[trip.id] = trip;
  if(Object.keys(this.dashboardTripsById).length < this.maxDashboardTrips || 
        trip.id.indexOf(this.bookingWebsiteTripTag) > -1) {
    this.dashboardTripsById[trip.id] = trip;
  }
};

ActiveTripsTracker.prototype.updateTrip = function(trip) { 
  if(!this.activeTripsById.hasOwnProperty(trip.id)) {
    throw new Error('Trip ' + trip.id + ' does not exist');
  }
  this.activeTripsById[trip.id] = trip;
  if(this.dashboardTripsById.hasOwnProperty(trip.id)){
    this.dashboardTripsById[trip.id] = trip;
  }
  if(isNonActiveStatus(trip.status)) {
    this.deactivateTrip(trip);
  }
};

ActiveTripsTracker.prototype.deactivateTrip = function(trip) {
  if(!this.activeTripsById.hasOwnProperty(trip.id)) {
    throw new Error('Trip ' + trip.id + ' does not exist');
  }
  var activeTrips = this.activeTripsById;
  var dashboardTrips = this.dashboardTripsById;
  setTimeout(function(){
    var t = activeTrips[trip.id];
    if(t && isNonActiveStatus(t.status)) {
      delete activeTrips[trip.id];
      if(dashboardTrips.hasOwnProperty(trip.id)) {
        delete dashboardTrips[trip.id];
      }
    }
  }, this.tripRemovalSpan.asMilliseconds());
};

ActiveTripsTracker.prototype.getTrip = function(trip) {
  return this.activeTripsById[trip.id];
};

ActiveTripsTracker.prototype.getAll = function(status) {
  var trips = [];
  for(var id in this.activeTripsById) {
    var trip = this.activeTripsById[id];
    if(status === 'all' || trip.status === status) {
      trips.push(trip);
    }
  }
  return trips;
};

// Smaller list used by the website dashboard
ActiveTripsTracker.prototype.getDashboardTrips = function(status) {
  var trips = [];
  for(var id in this.dashboardTripsById) {
    var trip = this.activeTripsById[id];
    if(status === 'all' || trip.status === status) {
      trips.push(trip);
    }
  }
  return trips;
};

ActiveTripsTracker.prototype.getStats = function() {
  return {
    activeTrips: Object.keys(this.activeTripsById).length
  };
};

var isNonActiveStatus = function(status) {
  return status === 'complete' || status === 'rejected' || status === 'cancelled';
};

module.exports = new ActiveTripsTracker();