var moment = require('moment');

function ActiveTripsTracker() {
  this.activeTripsById = {};
  this.tripRemovalSpan = moment.duration(5, 'minutes');
  this.dashboardTripsByIdByStatus = {
      queued: {},
      dispatched: {},
      enroute: {},
      pickedup: {},
      complete: {},
      cancelled: {},
      rejected: {}
  };
  this.dashboardTripsByIdByStatus['new'] = {};
  this.maxDashboardTrips = 150;
  this.bookingWebsiteTripTag = 'web'; // Used to identify trips generated by demo website to ensure they show up on dashboard
}

ActiveTripsTracker.prototype.addTrip = function(trip) {
  if(this.activeTripsById.hasOwnProperty(trip.id)) {
    throw new Error('Trip ' + trip.id + ' already exists');
  }
  this.activeTripsById[trip.id] = trip;
  this.addDashboardTrip(trip);
};

ActiveTripsTracker.prototype.getDashboardTripListByStatus = function(status) {
  return this.dashboardTripsByIdByStatus[status];
};

ActiveTripsTracker.prototype.addDashboardTrip = function(trip) {
  var triplist = this.getDashboardTripListByStatus(trip.status);
  if(triplist && Object.keys(triplist).length < this.maxDashboardTrips && 
        !triplist.hasOwnProperty(trip.id)) {
    triplist[trip.id] = trip;
  }
};

ActiveTripsTracker.prototype.updateTrip = function(trip) { 
  if(!this.activeTripsById.hasOwnProperty(trip.id)) {
    throw new Error('Trip ' + trip.id + ' does not exist');
  }
  this.activeTripsById[trip.id] = trip;
  this.updateDashboardTrip(trip);
  if(isNonActiveStatus(trip.status)) {
    this.deactivateTrip(trip);
  }
};

ActiveTripsTracker.prototype.updateDashboardTrip = function(trip) {
  this.deleteDashboardTripFromPreviousLists(trip);
  this.addDashboardTrip(trip);
};

ActiveTripsTracker.prototype.deleteDashboardTripFromPreviousLists = function(trip) {
  for(var id in this.dashboardTripsByIdByStatus){
    delete this.dashboardTripsByIdByStatus[id][trip.id];
  }
};

ActiveTripsTracker.prototype.deactivateTrip = function(trip) {
  if(!this.activeTripsById.hasOwnProperty(trip.id)) {
    throw new Error('Trip ' + trip.id + ' does not exist');
  }
  var self = this;
  setTimeout(function(){
    var t = self.activeTripsById[trip.id];
    if(t && isNonActiveStatus(t.status)) {
      delete self.activeTripsById[trip.id];
      self.deleteDashboardTrip(trip);
    }
  }, this.tripRemovalSpan.asMilliseconds());
};

ActiveTripsTracker.prototype.deleteDashboardTrip = function(trip) {
  var triplist = this.getDashboardTripListByStatus(trip.status);
  if(triplist && triplist.hasOwnProperty(trip.id)) {
    delete triplist[trip.id];
  }
};

ActiveTripsTracker.prototype.getTrip = function(trip) {
  return this.activeTripsById[trip.id];
};

ActiveTripsTracker.prototype.getAll = function(status) {
  var trips = [];
  for(var id in this.activeTripsById) {
    var trip = this.activeTripsById[id];
    if(status === 'all' || trip.status === status) {
      trips.push(trip);
    }
  }
  return trips;
};

function pushTrips(triplist, tripsToPush) {
  for(var id in tripsToPush) {
    triplist.push(tripsToPush[id]);
  }
  return triplist;
}

// Smaller list used by the website dashboard
ActiveTripsTracker.prototype.getDashboardTrips = function(status) {
  var trips = [];
  if(status === 'new' || status === 'all') {
    pushTrips(trips, this.dashboardTripsByIdByStatus['new']);
  }
  if(status === 'queued' || status === 'all') {
    pushTrips(trips, this.dashboardTripsByIdByStatus.queued);
  }
  if(status === 'dispatched' || status === 'all') {
    pushTrips(trips, this.dashboardTripsByIdByStatus.dispatched);
  }
  if(status === 'enroute' || status === 'all') {
    pushTrips(trips, this.dashboardTripsByIdByStatus.enroute);
  }
  if(status === 'pickedup' || status === 'all') {
    pushTrips(trips, this.dashboardTripsByIdByStatus.pickedup);
  }
  if(status === 'complete' || status === 'all') {
    pushTrips(trips, this.dashboardTripsByIdByStatus.complete);
  }
  if(status === 'cancelled' || status === 'all') {
    pushTrips(trips, this.dashboardTripsByIdByStatus.cancelled);
  }
  if(status === 'rejected' || status === 'all') {
    pushTrips(trips, this.dashboardTripsByIdByStatus.rejected);
  }
  return trips;
};

ActiveTripsTracker.prototype.getStats = function() {
  stats = {
    activeTrips: Object.keys(this.activeTripsById).length,
    queued: 0,
    dispatched: 0,
    enroute: 0,
    pickedup: 0,
    complete: 0,
    cancelled: 0,
    rejected: 0,
    serviceLevels: [0, 0, 0, 0, 0]
  };
  stats['new'] = 0;
  
  var durations = [];
  var distances = [];
  for(var id in this.activeTripsById) {
    var trip = this.activeTripsById[id];
    if(trip) {
      stats[trip.status]++;
      if(trip.status === 'complete' || trip.status === 'pickedup') {
        stats.serviceLevels[trip.serviceLevel]++;
      }
      if(trip.status === 'complete') {
        durations.push(trip.duration);
        distances.push(trip.distance);
      }
    }
  }
  if(durations.length > 0) {
    stats.durations = getFrequencyDistribution(durations, 5, 'min.');
  }
  if(distances.length > 0) {
    stats.distances = getFrequencyDistribution(distances, 5, 'mi');
  }
  return stats;
};

function sortNumber(a,b) {
  return a - b;
}

var getFrequencyDistribution = function(values, classes, dataTypeName) {
  values = values.sort(sortNumber);
  var max = values[values.length-1];
  var min = values[0];
  var interval = (max - min) / classes;
  interval = interval > 1 ? Math.ceil(interval) : interval;
  
  if(max === min) {
    return {
      name: '< '+ (Math.round(max * 100) / 100) + ' ' + dataTypeName, 
      value: values.length
    };
  }
  
  var boundary = min + interval;
  var valuesByClass = [];
  var valueIndex = 0;
  for(var i = 0; i < classes; i++) {
    var valuesInClass = 0;
    var inClass = true;
    while(inClass && valueIndex < values.length) {
      var v = values[valueIndex];
      if(v <= boundary) {
        valuesInClass++;
        valueIndex++;
      } else {
        inClass = false;
      }
    }
    valuesByClass.push({
      name: '< '+ (Math.round(boundary * 100) / 100) + ' ' + dataTypeName, 
      value: valuesInClass
    });
    boundary += interval;
  }
  return valuesByClass;
};

var isNonActiveStatus = function(status) {
  return status === 'complete' || status === 'rejected' || status === 'cancelled';
};

module.exports = new ActiveTripsTracker();